In [49]:
import nltk
nltk.download("vader_lexicon")

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!


True

In [50]:
import numpy as np
import pandas as pd

In [51]:
data=pd.read_csv("twitter_training.csv")

In [52]:
data.head()

2401  Borderlands  Positive  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                              review  
0  I am coming to the borders and I will kill you...  
1  im getting on borderlands and i will kill you ...  
2  im coming on borderlands and i will murder you...  
3  im getting on borderlands 2 and i will murder ...  
4  im getting into borderlands and i can murder y...

In [53]:
data.isnull().sum()

2401             0
Borderlands      0
Positive         0
review         686
dtype: int64

In [54]:
data.dropna(inplace=True)

In [55]:
blanks=[]
for i,label,Bd,p,rv in data.itertuples():
  if type(rv)==str:
    if rv.isspace():
      blanks.append(i)
blanks

[2291,
 2993,
 3239,
 3935,
 4229,
 4409,
 4751,
 4865,
 4895,
 5417,
 5555,
 5969,
 6011,
 6077,
 6581,
 6695,
 6857,
 6899,
 7301,
 7805,
 8687,
 8873,
 9449,
 9491,
 9557,
 9983,
 10031,
 10139,
 10259,
 10415,
 10481,
 10547,
 10673,
 11321,
 11459,
 11543,
 12557,
 16589,
 17369,
 17663,
 20459,
 22031,
 22115,
 22571,
 23075,
 23345,
 23519,
 23537,
 25229,
 25235,
 25805,
 27083,
 27701,
 27923,
 28073,
 28223,
 28349,
 29843,
 30251,
 30725,
 31787,
 32315,
 32561,
 32573,
 33227,
 33287,
 33401,
 33413,
 33875,
 34145,
 34841,
 35027,
 35165,
 35537,
 35681,
 35903,
 35963,
 36179,
 36563,
 36899,
 36923,
 37079,
 37211,
 38495,
 39023,
 39665,
 39893,
 40121,
 40247,
 40373,
 40805,
 41363,
 41801,
 41807,
 42161,
 42221,
 42347,
 42599,
 42809,
 42863,
 42965,
 43403,
 43679,
 43925,
 43961,
 44645,
 45533,
 45707,
 46067,
 47015,
 48077,
 48569,
 48749,
 50177,
 50627,
 50639,
 50741,
 51449,
 52973,
 53117,
 53855,
 54041,
 54107,
 55031,
 55493,
 56039,
 56615,
 56729,
 5

In [56]:
data.drop(blanks,inplace=True)

In [57]:
data["Positive"].value_counts()

Positive
Neutral     30893
Negative    22312
Positive    20618
Name: count, dtype: int64

In [58]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sid=SentimentIntensityAnalyzer()

In [59]:
data["scores"]=data["review"].apply(lambda review:sid.polarity_scores(review))

In [62]:
data["compound_scores"]=data["scores"].apply(lambda score__dict:score__dict["compound"])

In [66]:
data["label"]=data["compound_scores"].apply(lambda c:"Positive" if c>0 else ("Negative" if c < 0 else "Neutral"))

In [67]:
data.head()

2401  Borderlands  Positive  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

                                              review  \
0  I am coming to the borders and I will kill you...   
1  im getting on borderlands and i will kill you ...   
2  im coming on borderlands and i will murder you...   
3  im getting on borderlands 2 and i will murder ...   
4  im getting into borderlands and i can murder y...   

                                              scores  compound_scores  \
0  {'neg': 0.343, 'neu': 0.657, 'pos': 0.0, 'comp...          -0.6908   
1  {'neg': 0.37, 'neu': 0.63, 'pos': 0.0, 'compou...          -0.6908   
2  {'neg': 0.37, 'neu': 0.63, 'pos': 0.0, 'compou...          -0.6908   
3  {'neg': 0.343, 'neu': 0.657, 'pos': 0.0, 'comp...          -0.6908   
4  {'neg': 0.37, 'neu': 0.63, 'pos': 0.0, 'compou...          -0.6908   

      label  
0  Negative  
1  Negative  
2  Negative  
3  Negative  
4  Negative

In [68]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [69]:
cm=confusion_matrix(data["Positive"],data["label"])
print(cm)

[[12810  3671  5831]
 [11014  5905 13974]
 [ 3562  3288 13768]]


In [70]:
print(classification_report(data["Positive"],data["label"]))

              precision    recall  f1-score   support

    Negative       0.47      0.57      0.52     22312
     Neutral       0.46      0.19      0.27     30893
    Positive       0.41      0.67      0.51     20618

    accuracy                           0.44     73823
   macro avg       0.45      0.48      0.43     73823
weighted avg       0.45      0.44      0.41     73823



In [71]:
accuracy_score(data["Positive"],data["label"])

0.44001192040421006